/*********************************************************************/
/*                                                                   */
/*  SYSTEM NAME..: CCL UTILITIES                                     */
/*                                                                   */
/*  COMMAND NAME.: WRKLDA                                            */
/*                                                                   */
/*  COMMAND DESC.: WORK WITH THE *LDA                                */
/*                                                                   */
/*  DATE.........: 17/07/98                                          */
/*                                                                   */
/*  AUTHOR.......: FRED MITCHELL                                     */
/*                                                                   */
/*            (C) COPYRIGHT CONCISE CONSULTING LTD., 1997            */
/*********************************************************************/
             CMD        PROMPT('Work with the *LDA')
